version: '3'
services:
  nightwatch_db:
    image: 'postgis/postgis:15-3.3'
    container_name: nightwatch_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: nightwatch
      POSTGRES_PASSWORD: nightwatch
      POSTGRES_USER: nightwatch
